### ISSUE TITLE
It does not work with act and require fingerprint

### ISSUE THREAD

**Issue by andrius** [nicklasfrahm/scp-action#3] opened 2021-06-15 10:38 UTC
Hello, I was trying all the options: 20, "20", 20s, "20s" and always receive this error below. I am using act to test workflow

```
[Deployment/Prepare the environment]   🐳  docker run image=ghcr.io/nicklasfrahm/scp-action:main platform= entrypoint=[] cmd=[]
| 2021/06/15 10:22:59 ❌ Failed to parse action timeout: time: invalid duration "${{ inputs.action_timeout }}"
```

If I push the code, then I get another error through GitHub action  log:

```
2021/06/15 10:35:59 ❌ Failed to connect to target: ssh: handshake failed: fingerprint mismatch: server fingerprint: blah
```

```yml
      - name: Download file via SSH
        uses: nicklasfrahm/scp-action@v0.3.0
        with:
          direction: download
          timeout: "5s"
          action_timeout: "20s"
```

**Comment by nicklasfrahm** [comment] 2021-06-15 12:05
@andrius The first issue, you describe is caused by a bug in `act` described in nektos/act#263.

The second issue is by design to enforce the usage of fingerprints for security. Is this feature critical for you?

**Comment by nicklasfrahm** [comment] 2021-06-15 12:49
There is a possible workaround to use the action `args` instead of `env`. I will look into it.

**Comment by nicklasfrahm** [comment] 2021-06-30 04:20
For now, adjusting the way how the configuration is passed requires more effort than I have capacity for at the moment. If you have the capacity, I would be more than willing to review your PR.

As for the fingerprint verification, I created #5, so I will close this for now.

**Closed as completed by nicklasfrahm** 2021-06-30 04:20 UTC
Labels: wontfix
